spring:
  application:
    name: gateway_service
  cloud:
    gateway:
      routes:
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/product/**
        - id: user_service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-headers:
              - "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083